### ISSUE TITLE
Several things which should be done before 1.0

### ISSUE THREAD

**Issue by Trumeet** [MiPushFramework/MiPushTester#1]
- [x] Add a complete document for users
- [x] Prevent push before the user is registered
- [ ] Fix bugs in code which is marked as `TODO` and `FIXME`
- [x] Get ready CI builds
- [x] Publish the first alpha APK
- [X] Publish on Google Play
- [x] Add Fabric analytics
- [x] Add update checking

**Comment by TimothyZhang023** [comment]
gugugugugu 占坑

**Comment by Trumeet** [comment]
@TimothyZhang023 不要在 GitHub 版聊.....

**Comment by Trumeet** [comment]
Publishing into Google Play is temporarily given up.

**Comment by Trumeet** [comment]
> Publishing into Google Play is temporarily given up.

Restored & Finished.
